{{- if .Values.repositories }}
{{- range $repo := .Values.repositories }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $repo.name }}-tekton-triggers-createwebhook
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - eventlisteners
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - delete
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $repo.name }}-tekton-triggers-createwebhook
secrets:
  - name: {{ $repo.secret }}
  - name: {{ $repo.key }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $repo.name }}-tekton-triggers-createwebhook
subjects:
- kind: ServiceAccount
  name: {{ $repo.name }}-tekton-triggers-createwebhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $repo.name }}-tekton-triggers-createwebhook
{{- end }}
{{- end }}