---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.application.environments.development }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    argocd.argoproj.io/sync-options: Prune=false
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-builder-image-puller-{{ .Values.application.environments.development }}
  namespace: {{ .Values.application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.sa.triggers }}
  namespace: {{ .Values.application.environments.development }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-builder-image-puller-{{ .Values.application.environments.production }}
  namespace: {{ .Values.application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.sa.triggers }}
  namespace: {{ .Values.application.environments.production }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.application.environments.production }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    argocd.argoproj.io/sync-options: Prune=false

