{{ $application := default dict .Values.application }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ $application.name }}-git
spec:
  type: git
  params:
    - name: url
    - name: revision
    - name: submodules