{{ $application := default dict .Values.application }}
{{- if .Values.repositories }}
{{- range $repo := .Values.repositories }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $application.name }}-{{ $repo.id }}-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
{{- end }}
{{- end }}