apiVersion: v2
name: tekton-demo
description: A tekton nodejs demo pipeline containing steps to build, deploy, test, and promote to production. It is integrated with github event listeners and automatic routes creation.
type: application
keywords:
  - tekton
  - pipeline
  - nodejs
  - github
maintainers: 
  - name: mvmaestri
icon: https://cd.foundation/wp-content/uploads/sites/78/2020/04/tekton-icon-color-1-300x300.png
version: 0.0.1
appVersion: 0.0.1
