apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-nodejs-app
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: ref
      description: git ref
      type: string
    - name: revision
      description: git unique head commit id
      type: string
    - name: revision-type
      description: revision type usually branch type
      type: string
    - name: revision-name
      description: revision name usually version or branch name
      type: string
    - name: author
      description: commit author username
      type: string
    - name: AUTHORS_API_KEY
      description: The version of the application
      default: 'authors-secret-api'
      type: string
  resources:
    inputs:
      - name: image
        type: image
  steps:
      - name: app-create
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            replace=$(inputs.params.revision-name)
            revisionName=${replace//./-}
            oc get deployment/$(inputs.params.revision-type)-$revisionName -n {{ .Values.application.environments.development }}
            if [[ $? -ne 0 ]]
            then
                oc new-app --name=$(inputs.params.revision-type)-$revisionName -i={{ .Values.application.name }}:$(inputs.params.revision-name) --namespace={{ .Values.application.environments.development }} --labels=app.name={{ .Values.application.name }}
            else
                echo "Application already exists."
            fi
      # ,app.author=$(inputs.params.author),app.revision-name=$revisionName,app.revision-type=$(inputs.params.revision-type)
      - name: app-expose
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            replace=$(inputs.params.revision-name)
            revisionName=${replace//./-}
            oc get svc $(inputs.params.revision-type)-$revisionName -n {{ .Values.application.environments.development }}
            if [[ $? -ne 0 ]]
            then
                oc expose svc/$(inputs.params.revision-type)-$(inputs.params.revision-name) -n {{ .Values.application.environments.development }}
            else
                echo "Application is already exposed."
            fi

      - name: app-labels
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            replace=$(inputs.params.revision-name)
            revisionName=${replace//./-} # replace . to / 
            oc label deployment/$(inputs.params.revision-type)-$revisionName app.kubernetes.io/name=$(inputs.params.revision-type)-$revisionName --overwrite -n {{ .Values.application.environments.development }}
            oc label deployment/$(inputs.params.revision-type)-$revisionName app.version=$revisionName --overwrite -n {{ .Values.application.environments.development }}
            oc label deployment/$(inputs.params.revision-type)-$revisionName app.revision-id=$(inputs.params.revision) --overwrite -n {{ .Values.application.environments.development }}
            oc label deployment/$(inputs.params.revision-type)-$revisionName app.revision-type=$(inputs.params.revision-type) --overwrite -n {{ .Values.application.environments.development }}
            oc label deployment/$(inputs.params.revision-type)-$revisionName app.revision-name=$revisionName --overwrite -n {{ .Values.application.environments.development }}
            oc label deployment/$(inputs.params.revision-type)-$revisionName app.author=$(inputs.params.author) --overwrite -n {{ .Values.application.environments.development }}
            
            oc set env deployment/$(inputs.params.revision-type)-$revisionName revision-id=$(inputs.params.revision) -n {{ .Values.application.environments.development }}
            oc set env deployment/$(inputs.params.revision-type)-$revisionName revision-type=$(inputs.params.revision-type) -n {{ .Values.application.environments.development }}
            oc set env deployment/$(inputs.params.revision-type)-$revisionName revision-name=$revisionName -n {{ .Values.application.environments.development }}
            oc set env deployment/$(inputs.params.revision-type)-$revisionName --from secret/$(inputs.params.AUTHORS_API_KEY) -n {{ .Values.application.environments.development }}

      - name: app-probes
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            replace=$(inputs.params.revision-name)
            revisionName=${replace//./-}
            oc set probe deployment/$(inputs.params.revision-type)-$revisionName --remove --readiness --liveness -n {{ .Values.application.environments.development }}
            oc set probe deployment/$(inputs.params.revision-type)-$revisionName --readiness --get-url=http://:8080/ --initial-delay-seconds=30 -n {{ .Values.application.environments.development }}

      - name: app-autoscale
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            replace=$(inputs.params.revision-name)
            revisionName=${replace//./-}
            if [ "$(inputs.params.revision-type)" == "release" ]; then
              oc get hpa $(inputs.params.revision-type)-$revisionName  -n {{ .Values.application.environments.development }}
              if [[ $? -ne 0 ]]
              then
                  oc autoscale deployment $(inputs.params.revision-type)-$revisionName \
                    --min 1 --max 2 --cpu-percent=75 \
                    --namespace {{ .Values.application.environments.development }}
              else
                  echo "Application autoscale is already configured."
              fi
            fi

      - name: app-triggers
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            replace=$(inputs.params.revision-name)
            revisionName=${replace//./-}
            oc set triggers deployment/$(inputs.params.revision-type)-$revisionName -n {{ .Values.application.environments.development }}