apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ .Values.application.name }}-helm
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: ref
      description: Git reference
    - name: repourl
      description: repository url from github payload
    - name: repofullname
      description: full name user-org/reponame from github
    - name: revision
      description: commit head unique id
      type: string
    - name: revision-type
      description: revision type
      type: string
    - name: revision-name
      description: revision name
      type: string
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: helm-prepare
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
          if [ -d "chart" ]; then
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
            cp /usr/local/bin/helm /workspace/source/{{ .Values.pipeline.build.s2i.context }}
          else
            echo "Chart does not exist"
          fi
      securityContext:
        runAsUser: 0

    - name: chart-lint
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
          ls -ls
          if [ -d "chart" ]; then
            ./helm lint chart
            ./helm template -f chart/values.yaml chart
          else
            echo "Chart does not exist"
          fi
      securityContext:
        runAsUser: 0

  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}