apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply
  namespace: {{ .Values.application.environments.cicd }}
spec:
  workspaces:
  - name: source
  params:
    - name: ref
      description: git ref
      type: string
    - name: repofullname
      type: string
    - name: revision
      description: git unique head commit id
      type: string
    - name: revision-short
      description: git unique head commit id short version
      type: string
    - name: revision-type
      description: revision type usually branch type
      type: string
    - name: revision-name
      description: revision name usually version or branch name
      type: string
  steps:
    - name: helm-prepare
      image: registry.redhat.io/rhel8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          cp /usr/local/bin/helm /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      securityContext:
        runAsUser: 0

    - name: helm-apply
      image: quay.io/openshift/origin-cli:latest
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
        ls -ls
        ./helm template -f chart/values.yaml chart | oc apply -f-
      securityContext:
        runAsUser: 0