apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ .Values.application.name }}-standards
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: ref
      description: Git reference
    - name: repourl
      description: repository url from github payload
    - name: repofullname
      description: full name user-org/reponame from github
    - name: revision
      description: commit head unique id
      type: string
    - name: revision-type
      description: revision type
      type: string
    - name: revision-name
      description: revision name
      type: string
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: code-prepare
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
          npm ping --registry {{ .Values.pipeline.nexus.host }} install
          if [[ $? -ne 0 ]]; then
            npm install --only-dev --unsafe-perm=true --allow-root
          else
            echo Using nexus
            npm --registry {{ .Values.pipeline.nexus.host }} install --only-dev --unsafe-perm=true --allow-root
          fi
      securityContext:
        runAsUser: 0

    - name: code-audit
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      command: ["/bin/bash", "-c"]
      args:
        - |-
          npm audit
      securityContext:
        runAsUser: 0

    - name: code-lint
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      command: ["/bin/bash", "-c"]
      args:
        - |-
          npm run lint
      securityContext:
        runAsUser: 0

    - name: code-test
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
          if [[ $(npm run | grep "^  test-unit" | wc -l) == "1" ]]; then
            npm run test-unit
          else
            echo "Not implemented (npm run test-unit)"
          fi
      securityContext:
        runAsUser: 0

    - name: code-coverage
      image: ubi8/nodejs-12
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
          if [[ $(npm run | grep "^  coverage" | wc -l) == "1" ]]; then
            npm run coverage
          else
            echo "Not implemented (npm run coverage)"
          fi
      securityContext:
        runAsUser: 0

  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}