---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ .Values.application.name }}-trigger-template-dev
  namespace: {{ .Values.application.environments.cicd }}
spec:
  # todo: upgade tekton
  # description: >-
  #   This `task` consumes data from the trigger binding file and fires a new pipelinerun with a pipeline as reference.
  params:
  - name: ref
    description: git reference or branch name
  - name: revision
    description: The revision of your git repository
  - name: repourl
    description: The url of your git repository
  - name: reponame
    description: The name of your git repository
  - name: repofullname
    description: The full name of your git repository
  - name: message
    description: commit message
  - name: author
    description: commit author username
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: $(params.reponame)-$(params.author)-
      namespace: {{ .Values.application.environments.cicd }}
      labels:
        webhooks.tekton.dev/repo: $(params.reponame)
        webhooks.tekton.dev/author: $(params.author)
    spec:
      serviceAccountName: tekton-triggers-sa
      params:
        - name: ref
          value: $(params.ref)
        - name: revision
          value: $(params.revision)
        - name: author
          value: $(params.author)
        - name: message
          value: $(params.message)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: DEPLOY_ENVIRONMENT
          value: 'nodejs-tekton-development'
        - name: PROMOTE_ENVIRONMENT
          value: 'nodejs-tekton-production'
        - name: APP_NAME
          value: {{ .Values.application.name }}
        - name: APP_VERSION
          value: $(params.revision)
        - name: AUTHORS_API_KEY
          value: 'authors-secret-api'
        - name: DEPLOY_PROJECT
          value: {{ .Values.application.environments.development }}
        - name: PROMOTE_PROJECT
          value: {{ .Values.application.environments.production }}
      pipelineRef:
        name: {{ .Values.pipeline.name }}
      resources:
        - name: nodejs-git
          resourceRef:
            name: nodejs-git
        - name: nodejs-image-development
          resourceRef:
            name: nodejs-image-development
        - name: nodejs-image-production
          resourceRef:
            name: nodejs-image-production
      workspaces:
        - name: shared-workspace
        - name: upload
        - name: release-notes
          # tekton recent version only
          # volumeClaimTemplate:
          #   spec:
          #     accessModes:
          #     - ReadWriteOnce
          #     resources:
          #       requests:
          #         storage: 500Mi