apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: run
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
    version: {{ .Values.application.version }}
spec:
  serviceAccountName: tekton-triggers-sa
  pipelineRef:
    name: {{ .Values.pipeline.name }}
  params:
    - name: DEPLOY_ENVIRONMENT
      value: 'nodejs-tekton-development'
    - name: PROMOTE_ENVIRONMENT
      value: 'nodejs-tekton-production'
  resources:
    - name: nodejs-git
      resourceRef:
        name: nodejs-git
    - name: nodejs-image-development
      resourceRef:
        name: nodejs-image-development
    - name: nodejs-image-production
      resourceRef:
        name: nodejs-image-production
      # todo: upgrade tekton
      # workspaces:
      #   - name: shared-workspace
      # volumeClaimTemplate:
      #   spec:
      #     accessModes:
      #     - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 500Mi